### ISSUE TITLE
Permission to add this to my MailDelivery post on the forum

### ISSUE THREAD

**Issue by d0p3t** [propstg/esx-maildelivery#1]
Hey,

This is not an issue but more a question.

Would you be okay with me **linking this repository on my MailDelivery topic on the FiveM forum**?

I know this esx addon is simple and doesn't do much other than listen for the events and add/remove player money, but I think people would appreciate it. Perhaps this would give you more traffic to your Github (and this repository) and people might want some more additions.

I'll ofcourse tag you in my post. Thank you for using my resource.

Kind regards,
Remco Troost (d0p3t)
![image](https://user-images.githubusercontent.com/11293676/49257127-92e73180-f431-11e8-82a2-ca19e3ec38dc.png)

**Comment by propstg** [comment]
Heya, 

I somehow didn't see this before, sorry!

I'm okay with it, thanks for asking. I'm glad you went ahead and did it, because I don't know if I would have seen this otherwise. :) I've been using the username blarglebottoms on the forum, but it's absolutely not a big deal. 

Thanks for your great resource!

**Comment by d0p3t** [comment]
Alright, Thanks! Yea I went ahead and added it into the topic for the resource to get more traction.

Happy new year!
